### ISSUE TITLE
Classification of Victory- and Honorcertificates

### ISSUE THREAD

**Issue by skyliam** [bjs-org/bjs-api#11] opened 2019-11-29 15:49 UTC
I want to add a feature which returns which kind of certificate the student gets.
Do you have any suggestions where I should add it? A new controller?

**Comment by aykborstelmann** [comment] 2019-11-29 15:53
You could rename the `StudentScoreController` to `StudentController` and add an endpoint `/paper` or `/classification` or any name you think is appropriate.

**Comment by aykborstelmann** [comment] 2019-11-29 15:59
Actually this is a duplicate of #7. Please have a look at this there.

**Comment by aykborstelmann** [comment] 2019-12-05 19:33
Wait with closing this issue, I want to show you something.

**Closed** 2019-12-05 19:35 UTC
Labels: duplicate, feature
